#!/bin/sh

REPOSITORY=/media/backup-disk/borg

pmount /dev/sdb1/ backup-disk

borg create -v --stats \
    $REPOSITORY::'{hostname}--{now:%Y-%m-%d}' \
    $HOME \
    --progress \
    --exclude $HOME/Downloads \
    --exclude $HOME/.fonts \
    --exclude $HOME/.gconf \
    --exclude $HOME/.gnome \
    --exclude $HOME/.vimrc \
    --exclude $HOME/.cache \
    --exclude $HOME/.config \
    --exclude $HOME/.gftp \
    --exclude $HOME/.log \
    --exclude $HOME/.links2 \
    --exclude $HOME/.local \
    --exclude $HOME/.gnupg \
    --exclude $HOME/.virtualenvs \
    --exclude $HOME/.mutt_colors_zenburn \
    --exclude $HOME/projects/verbally \
    --exclude '*.pyc' \
    --exclude '.venv*' \
    --exclude '__pycache__'

borg prune -v $REPOSITORY --prefix '{hostname}--' \
    --keep-daily=7 \
    --keep-weekly=4 \
    --keep-monthly=6 \
    --keep-yearly=5

pumount /media/backup-disk
